// Code generated by goctl. DO NOT EDIT.
// Source: patient.proto

package server

import (
	"context"

	"github.com/qas491/hospital/patient_srv/internal/logic"
	"github.com/qas491/hospital/patient_srv/internal/svc"
	"github.com/qas491/hospital/patient_srv/patient"
)

type MedicalServiceServer struct {
	svcCtx *svc.ServiceContext
	patient.UnimplementedMedicalServiceServer
}

func NewMedicalServiceServer(svcCtx *svc.ServiceContext) *MedicalServiceServer {
	return &MedicalServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MedicalServiceServer) ListDepartments(ctx context.Context, in *patient.ListDepartmentsRequest) (*patient.ListDepartmentsResponse, error) {
	l := logic.NewListDepartmentsLogic(ctx, s.svcCtx)
	return l.ListDepartments(in)
}

func (s *MedicalServiceServer) ListDoctors(ctx context.Context, in *patient.ListDoctorsRequest) (*patient.ListDoctorsResponse, error) {
	l := logic.NewListDoctorsLogic(ctx, s.svcCtx)
	return l.ListDoctors(in)
}

func (s *MedicalServiceServer) ListTimeSlots(ctx context.Context, in *patient.ListTimeSlotsRequest) (*patient.ListTimeSlotsResponse, error) {
	l := logic.NewListTimeSlotsLogic(ctx, s.svcCtx)
	return l.ListTimeSlots(in)
}

func (s *MedicalServiceServer) MakeAppointment(ctx context.Context, in *patient.MakeAppointmentRequest) (*patient.MakeAppointmentResponse, error) {
	l := logic.NewMakeAppointmentLogic(ctx, s.svcCtx)
	return l.MakeAppointment(in)
}

func (s *MedicalServiceServer) GetAppointment(ctx context.Context, in *patient.GetAppointmentRequest) (*patient.GetAppointmentResponse, error) {
	l := logic.NewGetAppointmentLogic(ctx, s.svcCtx)
	return l.GetAppointment(in)
}

func (s *MedicalServiceServer) CancelAppointment(ctx context.Context, in *patient.CancelAppointmentRequest) (*patient.CancelAppointmentResponse, error) {
	l := logic.NewCancelAppointmentLogic(ctx, s.svcCtx)
	return l.CancelAppointment(in)
}
