// Code generated by goctl. DO NOT EDIT.
// Source: patient.proto

package medicalservice

import (
	"context"

	"github.com/qas491/hospital/patient_srv/patient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Appointment               = patient.Appointment
	CancelAppointmentRequest  = patient.CancelAppointmentRequest
	CancelAppointmentResponse = patient.CancelAppointmentResponse
	Department                = patient.Department
	Doctor                    = patient.Doctor
	GetAppointmentRequest     = patient.GetAppointmentRequest
	GetAppointmentResponse    = patient.GetAppointmentResponse
	ListDepartmentsRequest    = patient.ListDepartmentsRequest
	ListDepartmentsResponse   = patient.ListDepartmentsResponse
	ListDoctorsRequest        = patient.ListDoctorsRequest
	ListDoctorsResponse       = patient.ListDoctorsResponse
	ListTimeSlotsRequest      = patient.ListTimeSlotsRequest
	ListTimeSlotsResponse     = patient.ListTimeSlotsResponse
	MakeAppointmentRequest    = patient.MakeAppointmentRequest
	MakeAppointmentResponse   = patient.MakeAppointmentResponse
	Patient                   = patient.Patient
	TimeSlot                  = patient.TimeSlot

	MedicalService interface {
		ListDepartments(ctx context.Context, in *ListDepartmentsRequest, opts ...grpc.CallOption) (*ListDepartmentsResponse, error)
		ListDoctors(ctx context.Context, in *ListDoctorsRequest, opts ...grpc.CallOption) (*ListDoctorsResponse, error)
		ListTimeSlots(ctx context.Context, in *ListTimeSlotsRequest, opts ...grpc.CallOption) (*ListTimeSlotsResponse, error)
		MakeAppointment(ctx context.Context, in *MakeAppointmentRequest, opts ...grpc.CallOption) (*MakeAppointmentResponse, error)
		GetAppointment(ctx context.Context, in *GetAppointmentRequest, opts ...grpc.CallOption) (*GetAppointmentResponse, error)
		CancelAppointment(ctx context.Context, in *CancelAppointmentRequest, opts ...grpc.CallOption) (*CancelAppointmentResponse, error)
	}

	defaultMedicalService struct {
		cli zrpc.Client
	}
)

func NewMedicalService(cli zrpc.Client) MedicalService {
	return &defaultMedicalService{
		cli: cli,
	}
}

func (m *defaultMedicalService) ListDepartments(ctx context.Context, in *ListDepartmentsRequest, opts ...grpc.CallOption) (*ListDepartmentsResponse, error) {
	client := patient.NewMedicalServiceClient(m.cli.Conn())
	return client.ListDepartments(ctx, in, opts...)
}

func (m *defaultMedicalService) ListDoctors(ctx context.Context, in *ListDoctorsRequest, opts ...grpc.CallOption) (*ListDoctorsResponse, error) {
	client := patient.NewMedicalServiceClient(m.cli.Conn())
	return client.ListDoctors(ctx, in, opts...)
}

func (m *defaultMedicalService) ListTimeSlots(ctx context.Context, in *ListTimeSlotsRequest, opts ...grpc.CallOption) (*ListTimeSlotsResponse, error) {
	client := patient.NewMedicalServiceClient(m.cli.Conn())
	return client.ListTimeSlots(ctx, in, opts...)
}

func (m *defaultMedicalService) MakeAppointment(ctx context.Context, in *MakeAppointmentRequest, opts ...grpc.CallOption) (*MakeAppointmentResponse, error) {
	client := patient.NewMedicalServiceClient(m.cli.Conn())
	return client.MakeAppointment(ctx, in, opts...)
}

func (m *defaultMedicalService) GetAppointment(ctx context.Context, in *GetAppointmentRequest, opts ...grpc.CallOption) (*GetAppointmentResponse, error) {
	client := patient.NewMedicalServiceClient(m.cli.Conn())
	return client.GetAppointment(ctx, in, opts...)
}

func (m *defaultMedicalService) CancelAppointment(ctx context.Context, in *CancelAppointmentRequest, opts ...grpc.CallOption) (*CancelAppointmentResponse, error) {
	client := patient.NewMedicalServiceClient(m.cli.Conn())
	return client.CancelAppointment(ctx, in, opts...)
}
