// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: patient.proto

package patient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 科室信息
type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_patient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{0}
}

func (x *Department) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 医生信息
type Doctor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId  int32                  `protobuf:"varint,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Profile       string                 `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Doctor) Reset() {
	*x = Doctor{}
	mi := &file_patient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctor) ProtoMessage() {}

func (x *Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctor.ProtoReflect.Descriptor instead.
func (*Doctor) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{1}
}

func (x *Doctor) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Doctor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Doctor) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *Doctor) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Doctor) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

// 预约时间段
type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DoctorId      int32                  `protobuf:"varint,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`                            // yyyy-MM-dd
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // HH:mm
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // HH:mm
	Available     int32                  `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_patient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{2}
}

func (x *TimeSlot) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TimeSlot) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *TimeSlot) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimeSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TimeSlot) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

// 预约信息
type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     int32                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      int32                  `protobuf:"varint,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DepartmentId  int32                  `protobuf:"varint,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	TimeslotId    int32                  `protobuf:"varint,5,opt,name=timeslot_id,json=timeslotId,proto3" json:"timeslot_id,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // pending, confirmed, cancelled
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_patient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{3}
}

func (x *Appointment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Appointment) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *Appointment) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *Appointment) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *Appointment) GetTimeslotId() int32 {
	if x != nil {
		return x.TimeslotId
	}
	return 0
}

func (x *Appointment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Appointment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 患者信息
type Patient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	IdCard        string                 `protobuf:"bytes,5,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_patient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{4}
}

func (x *Patient) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Patient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Patient) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Patient) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Patient) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

// 科室列表
type ListDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsRequest) Reset() {
	*x = ListDepartmentsRequest{}
	mi := &file_patient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsRequest) ProtoMessage() {}

func (x *ListDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{5}
}

type ListDepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departments   []*Department          `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsResponse) Reset() {
	*x = ListDepartmentsResponse{}
	mi := &file_patient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsResponse) ProtoMessage() {}

func (x *ListDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*ListDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{6}
}

func (x *ListDepartmentsResponse) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

// 医生列表
type ListDoctorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int32                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoctorsRequest) Reset() {
	*x = ListDoctorsRequest{}
	mi := &file_patient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoctorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoctorsRequest) ProtoMessage() {}

func (x *ListDoctorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoctorsRequest.ProtoReflect.Descriptor instead.
func (*ListDoctorsRequest) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{7}
}

func (x *ListDoctorsRequest) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type ListDoctorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctors       []*Doctor              `protobuf:"bytes,1,rep,name=doctors,proto3" json:"doctors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoctorsResponse) Reset() {
	*x = ListDoctorsResponse{}
	mi := &file_patient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoctorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoctorsResponse) ProtoMessage() {}

func (x *ListDoctorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoctorsResponse.ProtoReflect.Descriptor instead.
func (*ListDoctorsResponse) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{8}
}

func (x *ListDoctorsResponse) GetDoctors() []*Doctor {
	if x != nil {
		return x.Doctors
	}
	return nil
}

// 时间段列表
type ListTimeSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      int32                  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimeSlotsRequest) Reset() {
	*x = ListTimeSlotsRequest{}
	mi := &file_patient_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimeSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimeSlotsRequest) ProtoMessage() {}

func (x *ListTimeSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimeSlotsRequest.ProtoReflect.Descriptor instead.
func (*ListTimeSlotsRequest) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{9}
}

func (x *ListTimeSlotsRequest) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *ListTimeSlotsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ListTimeSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeslots     []*TimeSlot            `protobuf:"bytes,1,rep,name=timeslots,proto3" json:"timeslots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimeSlotsResponse) Reset() {
	*x = ListTimeSlotsResponse{}
	mi := &file_patient_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimeSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimeSlotsResponse) ProtoMessage() {}

func (x *ListTimeSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimeSlotsResponse.ProtoReflect.Descriptor instead.
func (*ListTimeSlotsResponse) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{10}
}

func (x *ListTimeSlotsResponse) GetTimeslots() []*TimeSlot {
	if x != nil {
		return x.Timeslots
	}
	return nil
}

// 预约
type MakeAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     int32                  `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      int32                  `protobuf:"varint,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DepartmentId  int32                  `protobuf:"varint,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	TimeslotId    int32                  `protobuf:"varint,4,opt,name=timeslot_id,json=timeslotId,proto3" json:"timeslot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAppointmentRequest) Reset() {
	*x = MakeAppointmentRequest{}
	mi := &file_patient_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAppointmentRequest) ProtoMessage() {}

func (x *MakeAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAppointmentRequest.ProtoReflect.Descriptor instead.
func (*MakeAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{11}
}

func (x *MakeAppointmentRequest) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *MakeAppointmentRequest) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *MakeAppointmentRequest) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *MakeAppointmentRequest) GetTimeslotId() int32 {
	if x != nil {
		return x.TimeslotId
	}
	return 0
}

type MakeAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeAppointmentResponse) Reset() {
	*x = MakeAppointmentResponse{}
	mi := &file_patient_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAppointmentResponse) ProtoMessage() {}

func (x *MakeAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAppointmentResponse.ProtoReflect.Descriptor instead.
func (*MakeAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{12}
}

func (x *MakeAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

// 查询预约
type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId int32                  `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_patient_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{13}
}

func (x *GetAppointmentRequest) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

type GetAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentResponse) Reset() {
	*x = GetAppointmentResponse{}
	mi := &file_patient_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentResponse) ProtoMessage() {}

func (x *GetAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{14}
}

func (x *GetAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

// 取消预约
type CancelAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId int32                  `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAppointmentRequest) Reset() {
	*x = CancelAppointmentRequest{}
	mi := &file_patient_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentRequest) ProtoMessage() {}

func (x *CancelAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CancelAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{15}
}

func (x *CancelAppointmentRequest) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

type CancelAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAppointmentResponse) Reset() {
	*x = CancelAppointmentResponse{}
	mi := &file_patient_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentResponse) ProtoMessage() {}

func (x *CancelAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentResponse.ProtoReflect.Descriptor instead.
func (*CancelAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{16}
}

func (x *CancelAppointmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_patient_proto protoreflect.FileDescriptor

const file_patient_proto_rawDesc = "" +
	"\n" +
	"\rpatient.proto\x12\apatient\"R\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x81\x01\n" +
	"\x06Doctor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\x05R\fdepartmentId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\aprofile\x18\x05 \x01(\tR\aprofile\"\xa3\x01\n" +
	"\bTimeSlot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\x05R\bdoctorId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\x05R\tavailable\"\xd6\x01\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x05R\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\x05R\bdoctorId\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\x05R\fdepartmentId\x12\x1f\n" +
	"\vtimeslot_id\x18\x05 \x01(\x05R\n" +
	"timeslotId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"t\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x17\n" +
	"\aid_card\x18\x05 \x01(\tR\x06idCard\"\x18\n" +
	"\x16ListDepartmentsRequest\"P\n" +
	"\x17ListDepartmentsResponse\x125\n" +
	"\vdepartments\x18\x01 \x03(\v2\x13.patient.DepartmentR\vdepartments\"9\n" +
	"\x12ListDoctorsRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x05R\fdepartmentId\"@\n" +
	"\x13ListDoctorsResponse\x12)\n" +
	"\adoctors\x18\x01 \x03(\v2\x0f.patient.DoctorR\adoctors\"G\n" +
	"\x14ListTimeSlotsRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\x05R\bdoctorId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"H\n" +
	"\x15ListTimeSlotsResponse\x12/\n" +
	"\ttimeslots\x18\x01 \x03(\v2\x11.patient.TimeSlotR\ttimeslots\"\x9a\x01\n" +
	"\x16MakeAppointmentRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x05R\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\x05R\bdoctorId\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\x05R\fdepartmentId\x12\x1f\n" +
	"\vtimeslot_id\x18\x04 \x01(\x05R\n" +
	"timeslotId\"Q\n" +
	"\x17MakeAppointmentResponse\x126\n" +
	"\vappointment\x18\x01 \x01(\v2\x14.patient.AppointmentR\vappointment\">\n" +
	"\x15GetAppointmentRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\x05R\rappointmentId\"P\n" +
	"\x16GetAppointmentResponse\x126\n" +
	"\vappointment\x18\x01 \x01(\v2\x14.patient.AppointmentR\vappointment\"A\n" +
	"\x18CancelAppointmentRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\x05R\rappointmentId\"5\n" +
	"\x19CancelAppointmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x85\x04\n" +
	"\x0eMedicalService\x12T\n" +
	"\x0fListDepartments\x12\x1f.patient.ListDepartmentsRequest\x1a .patient.ListDepartmentsResponse\x12H\n" +
	"\vListDoctors\x12\x1b.patient.ListDoctorsRequest\x1a\x1c.patient.ListDoctorsResponse\x12N\n" +
	"\rListTimeSlots\x12\x1d.patient.ListTimeSlotsRequest\x1a\x1e.patient.ListTimeSlotsResponse\x12T\n" +
	"\x0fMakeAppointment\x12\x1f.patient.MakeAppointmentRequest\x1a .patient.MakeAppointmentResponse\x12Q\n" +
	"\x0eGetAppointment\x12\x1e.patient.GetAppointmentRequest\x1a\x1f.patient.GetAppointmentResponse\x12Z\n" +
	"\x11CancelAppointment\x12!.patient.CancelAppointmentRequest\x1a\".patient.CancelAppointmentResponseB\vZ\t./patientb\x06proto3"

var (
	file_patient_proto_rawDescOnce sync.Once
	file_patient_proto_rawDescData []byte
)

func file_patient_proto_rawDescGZIP() []byte {
	file_patient_proto_rawDescOnce.Do(func() {
		file_patient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patient_proto_rawDesc), len(file_patient_proto_rawDesc)))
	})
	return file_patient_proto_rawDescData
}

var file_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_patient_proto_goTypes = []any{
	(*Department)(nil),                // 0: patient.Department
	(*Doctor)(nil),                    // 1: patient.Doctor
	(*TimeSlot)(nil),                  // 2: patient.TimeSlot
	(*Appointment)(nil),               // 3: patient.Appointment
	(*Patient)(nil),                   // 4: patient.Patient
	(*ListDepartmentsRequest)(nil),    // 5: patient.ListDepartmentsRequest
	(*ListDepartmentsResponse)(nil),   // 6: patient.ListDepartmentsResponse
	(*ListDoctorsRequest)(nil),        // 7: patient.ListDoctorsRequest
	(*ListDoctorsResponse)(nil),       // 8: patient.ListDoctorsResponse
	(*ListTimeSlotsRequest)(nil),      // 9: patient.ListTimeSlotsRequest
	(*ListTimeSlotsResponse)(nil),     // 10: patient.ListTimeSlotsResponse
	(*MakeAppointmentRequest)(nil),    // 11: patient.MakeAppointmentRequest
	(*MakeAppointmentResponse)(nil),   // 12: patient.MakeAppointmentResponse
	(*GetAppointmentRequest)(nil),     // 13: patient.GetAppointmentRequest
	(*GetAppointmentResponse)(nil),    // 14: patient.GetAppointmentResponse
	(*CancelAppointmentRequest)(nil),  // 15: patient.CancelAppointmentRequest
	(*CancelAppointmentResponse)(nil), // 16: patient.CancelAppointmentResponse
}
var file_patient_proto_depIdxs = []int32{
	0,  // 0: patient.ListDepartmentsResponse.departments:type_name -> patient.Department
	1,  // 1: patient.ListDoctorsResponse.doctors:type_name -> patient.Doctor
	2,  // 2: patient.ListTimeSlotsResponse.timeslots:type_name -> patient.TimeSlot
	3,  // 3: patient.MakeAppointmentResponse.appointment:type_name -> patient.Appointment
	3,  // 4: patient.GetAppointmentResponse.appointment:type_name -> patient.Appointment
	5,  // 5: patient.MedicalService.ListDepartments:input_type -> patient.ListDepartmentsRequest
	7,  // 6: patient.MedicalService.ListDoctors:input_type -> patient.ListDoctorsRequest
	9,  // 7: patient.MedicalService.ListTimeSlots:input_type -> patient.ListTimeSlotsRequest
	11, // 8: patient.MedicalService.MakeAppointment:input_type -> patient.MakeAppointmentRequest
	13, // 9: patient.MedicalService.GetAppointment:input_type -> patient.GetAppointmentRequest
	15, // 10: patient.MedicalService.CancelAppointment:input_type -> patient.CancelAppointmentRequest
	6,  // 11: patient.MedicalService.ListDepartments:output_type -> patient.ListDepartmentsResponse
	8,  // 12: patient.MedicalService.ListDoctors:output_type -> patient.ListDoctorsResponse
	10, // 13: patient.MedicalService.ListTimeSlots:output_type -> patient.ListTimeSlotsResponse
	12, // 14: patient.MedicalService.MakeAppointment:output_type -> patient.MakeAppointmentResponse
	14, // 15: patient.MedicalService.GetAppointment:output_type -> patient.GetAppointmentResponse
	16, // 16: patient.MedicalService.CancelAppointment:output_type -> patient.CancelAppointmentResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_patient_proto_init() }
func file_patient_proto_init() {
	if File_patient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patient_proto_rawDesc), len(file_patient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patient_proto_goTypes,
		DependencyIndexes: file_patient_proto_depIdxs,
		MessageInfos:      file_patient_proto_msgTypes,
	}.Build()
	File_patient_proto = out.File
	file_patient_proto_goTypes = nil
	file_patient_proto_depIdxs = nil
}
